Recruiter view
Web-Team-IITI-Gymkhana/tpc-frontend pull request #76
Opened 2024-06-22 06:49 UTC by Princekumarofficial

1. Recruiter Profile with view and update

2024-06-23 10:05 UTC, Princekumarofficial commented
1. Events about Job
2. Appliactions for job
3. Made Sidebar dashboard responsive

2024-06-25 06:37 UTC, AryanGKulkarni requested changes

2024-06-25 06:37 UTC, AryanGKulkarni commented on src/helpers/recruiter/api.ts
> +}
make a separate file in helpers/recruiter named types.ts and store all the interfaces there

2024-06-25 06:37 UTC, AryanGKulkarni commented on src/app/(routes)/recruiter/profile/edit/page.tsx
why is there a different page for profile edit

2024-06-29 07:00 UTC, AryanGKulkarni approved these changes

2024-06-29 07:00 UTC, merged